package View;

import Model.HeaderTableModel;
import Model.InvoiceHeader;
import Model.InvoiceLine;
import Model.InvoiceLineTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Writer;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hd STORE
 */
public class MyFrame extends javax.swing.JFrame implements ActionListener, ListSelectionListener{

    /**
     * Creates new form MyFrame
     */
    public MyFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CreateNewInvoice = new javax.swing.JButton();
        CreateNewInvoice.setActionCommand("newInv");
        CreateNewInvoice.addActionListener(this);
        DeleteInvoice = new javax.swing.JButton();
        DeleteInvoice.setActionCommand("delInv");
        DeleteInvoice.addActionListener(this);
        jScrollPane1 = new javax.swing.JScrollPane();
        HeaderTable = new javax.swing.JTable();
        HeaderTable.getSelectionModel().addListSelectionListener(this);

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        invNum = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        invDateTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        custNameTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        invTotal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LineTable = new javax.swing.JTable();
        CreateNewItem = new javax.swing.JButton();
        CreateNewItem.setActionCommand("newItem");
        CreateNewItem.addActionListener(this);
        DeleteItem = new javax.swing.JButton();
        DeleteItem.setActionCommand("delItem");
        DeleteItem.addActionListener(this);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loadFileMenuItem = new javax.swing.JMenuItem();
        loadFileMenuItem.setActionCommand("load");
        loadFileMenuItem.addActionListener(this);

        saveFileMenuItem = new javax.swing.JMenuItem();
        saveFileMenuItem.setActionCommand("save");
        saveFileMenuItem.addActionListener(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Invoice Table");

        CreateNewInvoice.setText("Create New Invoice");
        CreateNewInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewInvoiceActionPerformed(evt);
            }
        });

        DeleteInvoice.setText("Delete Invoice");

        HeaderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Date", "Customer", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        HeaderTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(HeaderTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(CreateNewInvoice)
                        .addGap(55, 55, 55)
                        .addComponent(DeleteInvoice)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateNewInvoice)
                    .addComponent(DeleteInvoice))
                .addContainerGap())
        );

        jLabel2.setText("Invoice Number");

        jLabel4.setText("Invoice Date");

        invDateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invDateTFActionPerformed(evt);
            }
        });

        jLabel5.setText("Customer Name");

        custNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custNameTFActionPerformed(evt);
            }
        });

        jLabel6.setText("Invoice Total");

        jLabel8.setText("Invoice Items");

        LineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Item Name", "Item Price", "Count", "Item Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        LineTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(LineTable);

        CreateNewItem.setText("Insert new Item");
        CreateNewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewItemActionPerformed(evt);
            }
        });

        DeleteItem.setText("Delete Item");
        DeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(custNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4))
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(invDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(invTotal))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(CreateNewItem)
                                .addGap(82, 82, 82)
                                .addComponent(DeleteItem))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(invNum)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(invNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(invDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(custNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(invTotal))
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateNewItem)
                    .addComponent(DeleteItem))
                .addContainerGap())
        );

        jMenu1.setText("File");

        loadFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        loadFileMenuItem.setText("Load File");
        loadFileMenuItem.setToolTipText("");
        loadFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(loadFileMenuItem);

        saveFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saveFileMenuItem.setText("Save File");
        saveFileMenuItem.setToolTipText("");
        jMenu1.add(saveFileMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateNewInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateNewInvoiceActionPerformed

    private void invDateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invDateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invDateTFActionPerformed

    private void custNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custNameTFActionPerformed

    private void CreateNewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateNewItemActionPerformed

    private void DeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteItemActionPerformed

    private void loadFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadFileMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateNewInvoice;
    private javax.swing.JButton CreateNewItem;
    private javax.swing.JButton DeleteInvoice;
    private javax.swing.JButton DeleteItem;
    private javax.swing.JTable HeaderTable;
    private javax.swing.JTable LineTable;
    private javax.swing.JTextField custNameTF;
    private javax.swing.JTextField invDateTF;
    private javax.swing.JLabel invNum;
    private javax.swing.JLabel invTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem loadFileMenuItem;
    private javax.swing.JMenuItem saveFileMenuItem;
    // End of variables declaration//GEN-END:variables
    private ArrayList<InvoiceHeader> invoices = new ArrayList<>();
    private HeaderTableModel headermodel;
    private InvoiceLineTableModel LinesModel;
    private Dialog dialog;
    private Dialog2 dialog2;
            
    @Override
    public void actionPerformed(ActionEvent e) {
        
        if(e.getActionCommand().equals("load")){
            
            try {
                loadFiles();
            } catch (Exception ex) {
                Logger.getLogger(MyFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if (e.getActionCommand().equals("save")){
            try {
                saveData();
            } catch (Exception ex) {
                Logger.getLogger(MyFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if (e.getActionCommand().equals("newInv")) {
            createInv();
        }
        else if(e.getActionCommand().equals("delInv")){
            
            deleteInv();
        }
        else if(e.getActionCommand().equals("newItem")){
            Additem();
        }
        else if(e.getActionCommand().equals("delItem")){
            
            deleteItem();
        }
        else if(e.getActionCommand().equals("createinvOK")){
            
            okInv();
        }
        else if(e.getActionCommand().equals("Cancelcreateinv")){
            
            cancelInv();
        }
        else if(e.getActionCommand().equals("AddItemOK")){
            
            okItem();
        }
        else if(e.getActionCommand().equals("CancelItem")){
            
            cancelItem();
        }
    
    }
    
    @Override
    public void valueChanged(ListSelectionEvent e) {
        
        selectRow();
    }
    
    private void loadFiles() throws Exception 
    {
        invoices.clear();
        JOptionPane.showMessageDialog(this,"Please select invoice header file", "Invoice Header", JOptionPane.WARNING_MESSAGE);
        JFileChooser fc = new JFileChooser();
        int result = fc.showOpenDialog(this);
        
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = fc.getSelectedFile();
            FileReader fr = new FileReader(selectedFile);
            BufferedReader br = new BufferedReader(fr);
            String line = null;
           
            while((line = br.readLine()) != null)
            {
                String[] headerFields = line.split(",");
                String numstr = headerFields[0];
                String date = headerFields[1];
                String custName = headerFields[2];
             
                int num = Integer.parseInt(numstr);
                InvoiceHeader header = new InvoiceHeader(num, date, custName);
                invoices.add(header);
            }
            
            br.close();
            fr.close();
            
            JOptionPane.showMessageDialog(this, "Show invoice lines file", "Invoice Lines", JOptionPane.WARNING_MESSAGE);
            result = fc.showOpenDialog(this);
            if(result == JFileChooser.APPROVE_OPTION)
            {
                selectedFile = fc.getSelectedFile();
                fr = new FileReader(selectedFile);
                br = new BufferedReader(fr);
                
                line = null;
           
                while((line = br.readLine()) != null)
                {
                    String[] LineFields = line.split(",");
                    String invnumstr = LineFields[0];
                    String ItemName = LineFields[1];
                    String pricestr = LineFields[2];
                    String countstr = LineFields[3];

                    int invnum = Integer.parseInt(invnumstr);
                    double price = Double.parseDouble(pricestr);
                    int count = Integer.parseInt(countstr);
                    InvoiceHeader header = searchHeader(invnum);
                   
                    InvoiceLine invline = new InvoiceLine(ItemName, price, count, header);
                    header.addline(invline);
                }
            
                br.close();
                fr.close();
                headermodel = new HeaderTableModel(invoices);
                HeaderTable.setModel(headermodel);
            }
        }
    }
    
    private void saveData() throws Exception {
         
        JFileChooser fc = new JFileChooser();
        int result = fc.showSaveDialog(null);
        
        
        if(result == JFileChooser.APPROVE_OPTION ){
            
            File myFile = fc.getSelectedFile();
            PrintWriter fw = new PrintWriter(myFile);
            BufferedWriter bw = new BufferedWriter(fw);
          
            for(InvoiceHeader header:invoices){
             
                fw.printf("%d,%s,%s",header.getNum(),header.getDate().toString(),header.getName());

                bw.newLine();
                fw.println();
                
            }
            JOptionPane.showMessageDialog(this, "saved!", "information message",JOptionPane.INFORMATION_MESSAGE);
            bw.close();
            fw.close();
        }
        
        
        fc = new JFileChooser();
        result = fc.showSaveDialog(null);
        
        if(result == JFileChooser.APPROVE_OPTION ){
            
            File myFile = fc.getSelectedFile();
            PrintWriter fw = new PrintWriter(myFile);
            BufferedWriter bw = new BufferedWriter(fw);
          
            for(InvoiceHeader header:invoices ){
                for(InvoiceLine Lines :header.getLines()){
                    
                fw.printf("%s ,%s,%d",Lines.getItemName(),""+Lines.getPrice(),Lines.getCount());
                bw.newLine();
                fw.println();
            }
            }

            JOptionPane.showMessageDialog(this, "saved!", "information message",JOptionPane.INFORMATION_MESSAGE);
            bw.close();
            fw.close();
        }
       }
 
       
    
   private InvoiceHeader searchHeader(int num){
       
       for(InvoiceHeader header: invoices){
           
           if(header.getNum() == num){
               
               return header;
           }
       }
       return null;
   }
    
    private void selectRow(){
        
        int rowIndex = HeaderTable.getSelectedRow();
        if(rowIndex >= 0 )
        {
        InvoiceHeader row = headermodel.getInvoices().get(rowIndex);
        
        invNum.setText(""+row.getNum());
        invDateTF.setText(row.getDate());
        custNameTF.setText(row.getName());
        invTotal.setText(""+row.getInvTotal());
        
        ArrayList<InvoiceLine> lines = row.getLines();
        LinesModel = new InvoiceLineTableModel(lines);
        LineTable.setModel(LinesModel);
        LinesModel.fireTableDataChanged();
        }
        
    }
    
    
    private void createInv(){
        dialog = new Dialog(this);
        dialog.setVisible(true);
    }

    private void okInv(){
        
        String custName = dialog.getCustnameTF().getText();
        String Date = dialog.getDateTF().getText();
        dialog.setVisible(false);
        
        InvoiceHeader newheader = new InvoiceHeader(getsecondIndex(), Date, custName);
        invoices.add(newheader);
        headermodel.fireTableDataChanged();
        
    }
    
    private void cancelInv(){
        
        dialog.setVisible(false);
    }
    
    private int getsecondIndex(){
        
        int index = 0;
        for(InvoiceHeader h: invoices){
            
            if(h.getNum() > index){
                
                index = h.getNum();
            }
        }
        return index+1;
    }

    private void Additem() {
        
        dialog2 = new Dialog2(this);
        dialog2.setVisible(true);
    }
    
    private void cancelItem() {
       
        dialog2.setVisible(false);
    }

    private void okItem() {
          
        String itemName = dialog2.getItemnameTF().getText();
        String countstr = dialog2.getCountTF().getText();
        String pricestr = dialog2.getPriceTF().getText();
        dialog2.setVisible(false);
        
        int count = Integer.parseInt(countstr);
        double price = Double.parseDouble(pricestr);
         
        InvoiceHeader header =invoices.get(HeaderTable.getSelectedRow());
        InvoiceLine newline = new InvoiceLine(itemName, price , count ,header);
        header.addline(newline);
        
        LinesModel.fireTableDataChanged();
        headermodel.fireTableDataChanged();
        invTotal.setText(""+header.getInvTotal());
    }

    private void deleteItem() {
  
        int rowIndex = LineTable.getSelectedRow();
        
        if(rowIndex != -1){
            LinesModel.removeRow(rowIndex);
        }
      
        LinesModel.fireTableDataChanged();
        headermodel.fireTableDataChanged();
    }

    private void deleteInv() {
        
        int rowindex = HeaderTable.getSelectedRow();
        if(rowindex != -1){
        headermodel.removeRow(rowindex);
        }
        
        headermodel.fireTableDataChanged();
    }

}
